# Generated by Django 5.2.6 on 2025-12-26 04:30

import django.db.models.deletion
import home.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_cliprequest_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("video_id", models.CharField(blank=True, max_length=100)),
                ("video_duration", models.IntegerField(blank=True, null=True)),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("channel_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="channel_name",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="clip_480p",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="clip_480p_size",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="clip_720p",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="clip_720p_size",
        ),
        migrations.RemoveField(
            model_name="cliprequest",
            name="original_title",
        ),
        migrations.AlterField(
            model_name="cliprequest",
            name="clip_duration",
            field=models.IntegerField(
                blank=True, help_text="clip duration in seconds", null=True
            ),
        ),
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("clip", models.FileField(upload_to=home.models.clip_file_path)),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, help_text="clip size in mb", null=True
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="clip duration in seconds", null=True
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1080p", "1080p"),
                            ("720p", "720p"),
                            ("480p", "480p"),
                            ("360p", "360p"),
                            ("240p", "240p"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clip_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="home.cliprequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cliprequest",
            name="video_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.videodetail",
            ),
        ),
    ]
