# Generated by Django 5.2.6 on 2025-12-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_videodetail_remove_cliprequest_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="size",
            field=models.FloatField(blank=True, help_text="clip size in mb", null=True),
        ),
    ]
