# Generated by Django 5.2.6 on 2025-12-28 15:08

import django.db.models.deletion
import home.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_cliprequest_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeedEditRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "uploaded_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.speed_edit_upload_path,
                    ),
                ),
                (
                    "speed_factor",
                    models.FloatField(
                        help_text="Speed multiplier (e.g., 0.5, 1.5, 2.0)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "output_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=home.models.speed_edit_output_path,
                    ),
                ),
                (
                    "output_size",
                    models.FloatField(
                        blank=True, help_text="Output file size in MB", null=True
                    ),
                ),
                (
                    "output_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("original_duration", models.IntegerField(blank=True, null=True)),
                ("original_size", models.FloatField(blank=True, null=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Time taken in seconds", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "source_clip",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to existing clip from portal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.clip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "speed_edit_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
