# Generated by Django 5.2.6 on 2026-01-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_speededitrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="speededitrequest",
            name="rq_job_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
