# Generated by Django 5.2.6 on 2026-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_speededitrequest_rq_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliprequest",
            name="proxy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
