# Generated by Django 5.2.6 on 2026-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_cliprequest_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="speededitrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
