# Generated by Django 5.2.6 on 2026-03-01 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_cliprequest_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClipAnalytics",
        ),
    ]
