"""
Django settings for yt_helper project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)


ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', []).split(',')
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "home",

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_extensions',
    'django_rq',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',#cors setting
    'django.middleware.gzip.GZipMiddleware', # for text compression (reduces the response size of apis)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'yt_helper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["email_templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yt_helper.wsgi.application'
AUTH_USER_MODEL = 'home.User'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    # "default": {
    #     "ENGINE": "django.db.backends.postgresql_psycopg2",
    #     "NAME": os.environ.get("DB_NAME", ""),
    #     "USER": os.environ.get("DB_USERNAME", ""),
    #     "PASSWORD": os.environ.get("DB_PASSWORD", ""),
    #     "HOST": os.environ.get("DB_HOST", ""),
    #     "PORT": "",
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', ['http://127.1.1:8000']).split(',')

#cors setting

CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', []).split(',')


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Expose headers (important for file downloads)
CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
    'Content-Type',
    'Content-Length',
]


ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL","divyanshusoni.relish@gmail.com")
ADMIN_PHONE = os.environ.get("ADMIN_PHONE","")
FRONTEND_URL = os.environ.get("FRONTEND_URL","http://localhost:3000")
BREVO_API_KEY = os.environ.get("BREVO_API_KEY","")
RAPIDAPI_KEY = os.environ.get("RAPIDAPI_KEY","")
DEFAULT_PASSWORD = os.environ.get("DEFAULT_PASSWORD")

PROXIES = os.environ.get("PROXIES", "").split(",")
COOKIES_FILE = os.environ.get("COOKIES_FILE", "")
REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
}


FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024 # 50 Mb limit

# Redis and Django-RQ Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)
REDIS_DB = os.environ.get('REDIS_DB', 0)

RQ_QUEUES = {
    'default': {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': REDIS_DB,
        'DEFAULT_TIMEOUT': 360,
    }
}

LOGFILES_DIRECTORY_NAME = "log_files"

if not os.path.exists(LOGFILES_DIRECTORY_NAME):
    os.makedirs(LOGFILES_DIRECTORY_NAME)

LOGGING = {  
    'version': 1,  
    # Version of logging  
    'disable_existing_loggers': False,  
    'formatters': {
        'default': {
          
            'format': '%(asctime)s  %(levelname)s %(pathname)s ln. no. %(lineno)d %(message)s',
        }
    }, 
    # Handlers ####
    'handlers': {  
        'warning_file': {  
            'level': 'WARNING',  
            'class': 'logging.FileHandler',  
            'filename': f'log_files/warning.log',
            'formatter': 'default'  
        },
        'info_file': {  
            'level': 'INFO',  
            'class': 'logging.FileHandler',  
            'filename': f'log_files/info.log',
            'formatter': 'default'  
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'default'
        },
    },  
    # Loggers ####  
    'loggers': {  
        'django': {  
            'handlers': ['warning_file','info_file','console'],  
            'level': 'DEBUG',  
            'propagate': True,  
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG')  
        },  
    },  
}  
import logging 
logger = logging.getLogger('django')

